environment:
  GITHUB_TOKEN:
    secure: E1HpiZf9OJuc8XPGA57hJbCQlMWVCPVBePHiWF/BgmJ/+e/2OplyifiS/x8CJtcw
  matrix:
    - nodejs_version: "4"
      deploy: "true"
    - nodejs_version: "5"
      electron: "0.37.8"
    - nodejs_version: "6"
      electron: "1.1.3"
    - nodejs_version: "6"
      electron: "1.4.3"

platform:
  - x64
  - x86

build: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - IF DEFINED ELECTRON (npm install electron-prebuilt@%ELECTRON%)
  - IF DEFINED ELECTRON (npm install -g node-gyp)
  # We always need to rebuild for electron even for electron <= 1.1.3
  - IF DEFINED ELECTRON (node-gyp rebuild --runtime=electron --target=%ELECTRON% --disturl=https://atom.io/download/atom-shell --build-from-source)


test_script:
  - IF DEFINED ELECTRON (appveyor-retry call npm run test:electron) ELSE (appveyor-retry call npm test)

deploy_script:
  - IF "%deploy%;%appveyor_repo_tag%"=="true;true" (npm install prebuild -g & prebuild --all -u %GITHUB_TOKEN%)
